src/ComputerEquipmentMS/ComputerEquipmentMS/Models/Domain/ComponentCategory.cs
namespace ComputerEquipmentMS.Models.Domain;

public class ComponentCategory : IIdentifiable<int>
{
    public int Id { get; set; }
    public required string Name { get; set; }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/ComponentCategories/ComponentCategoriesViewModel.cs
using System.Collections.ObjectModel;

namespace ComputerEquipmentMS.ViewModels.ComponentCategories;

public class ComponentCategoriesViewModel : Collection<ComponentCategoryViewModel>
{
    public ComponentCategoriesViewModel(ICollection<ComponentCategoryViewModel> componentCategoryViewModels)
        : base(componentCategoryViewModels.ToList())
    {
    }

    public ComponentCategoriesViewModel()
    {
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/ComponentCategories/ComponentCategoryViewModel.cs
namespace ComputerEquipmentMS.ViewModels.ComponentCategories;

public class ComponentCategoryViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/ComponentCategoriesViewModel.cs
using System.Collections.ObjectModel;

namespace ComputerEquipmentMS.ViewModels;

public class ComponentCategoriesViewModel : Collection<ComponentCategoryViewModel>
{
    public ComponentCategoriesViewModel(ICollection<ComponentCategoryViewModel> componentCategoryViewModels)
        : base(componentCategoryViewModels.ToList())
    {
    }

    public ComponentCategoriesViewModel()
    {
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/ComponentCategoryViewModel.cs
namespace ComputerEquipmentMS.ViewModels;

public class ComponentCategoryViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/ComponentCategoriesController.cs
using ComputerEquipmentMS.Constants;
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.ComponentCategories;
using ComputerEquipmentMS.ViewModels.Components;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ComputerEquipmentMS.Controllers;

public class ComponentCategoriesController : ControllerBase
{
    private readonly IRepository<ComponentCategory, int> _componentCategoriesRepository;
    private readonly NpgsqlStoredFunctionsExecutor _executor;

    public ComponentCategoriesController(
        IRepository<ComponentCategory, int> componentCategoriesRepository,
        NpgsqlStoredFunctionsExecutor executor,
        ILogger<ComponentCategoriesController> logger) : base(logger)
    {
        _componentCategoriesRepository = componentCategoriesRepository;
        _executor = executor;
    }
    
    

    [HttpGet]
    public IActionResult Index()
    {
        var categories = _componentCategoriesRepository.GetAll();
        var categoriesVm = categories.Adapt<ComponentCategoriesViewModel>(); 
        
        return View(categoriesVm);
    }

    
    
    [HttpGet]
    public IActionResult Details(int id)
    {
        var category = _componentCategoriesRepository.GetById(id);
        if (category is null) return HandleError($"cannot find {nameof(ComponentCategory)} with id = {id}");

        var components = _executor.GetComponentsByCategory(id);
        var componentsVm = components.Adapt<ComponentsViewModel>();
        ViewBag.Components = componentsVm; 
        
        var categoryVm = category.Adapt<ComponentCategoryViewModel>();
        return View(categoryVm);
    }
    
    
    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Create(ComponentCategoryViewModel categoryViewModel)
    {
        var category = categoryViewModel.Adapt<ComponentCategory>();
        _componentCategoriesRepository.Add(category);

        return RedirectToAction(nameof(Index));
    }



    [HttpGet]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Edit(int id)
    {
        var category = _componentCategoriesRepository.GetById(id);
        if (category is null) return HandleError($"cannot find {nameof(ComponentCategory)} with id = {id}");

        var categoryVm = category.Adapt<ComponentCategoryViewModel>();
        return View(categoryVm);
    }
    
    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Edit(ComponentCategoryViewModel categoryViewModel)
    {
        var category = categoryViewModel.Adapt<ComponentCategory>();
        var editResult = _componentCategoriesRepository.Edit(category);
        return editResult 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while editing {nameof(ComponentCategory)}: element with id {category.Id} was not edited");
    }
    
    

    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Remove(int id)
    {
        var removeResult = _componentCategoriesRepository.Remove(id);
        return removeResult 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while removing {nameof(ComponentCategory)}: element with id {id} was not removed");
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/ComponentCategories/Create.cshtml
@using static ComputerEquipmentMS.Views.Common.Constants
@model ComputerEquipmentMS.ViewModels.ComponentCategories.ComponentCategoryViewModel

<h2 class="display-4">Добавление категории комплектующих</h2>

<div>
    <form asp-controller="ComponentCategories" asp-action="Create" method="post">
        <div class="form-floating" style="margin-top: 20px">
            <input type="text" id="nameInput" asp-for="Name" class="form-control" required pattern="@DenyOnlySpacesOrSpaceFramesStringsRegex">
            <label for="nameInput">Название</label>
        </div>

        <div style="display: flex; width: 100%; margin-top: 20px">
            <button type="submit" class="btn btn-light" style="flex-grow: 1; flex-basis: 0">Сохранить</button>
            <button type="button" onclick="history.back()" class="btn btn-light" style="flex-grow: 1; flex-basis: 0; margin-left: 10px">Отменить</button>
        </div>
    </form>
</div>

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/ComponentCategories/Details.cshtml
@using ComputerEquipmentMS.ViewModels.Components
@model ComputerEquipmentMS.ViewModels.ComponentCategories.ComponentCategoryViewModel

@{
    var category = Model;

    var components = (ComponentsViewModel) ViewBag.Components;
}

<div>
    <h2 class="display-6">Компоненты из категории "@category.Name"</h2>
    
    <table class="table table-hover">
        <thread>
            <tr>
                <th>Название</th>
                <th>Производитель</th>
                <th>Спецификации</th>
                <th>Стоимость закупки у производителя</th>
                <th>Гарантия производителя</th>
            </tr>
        </thread>
        @foreach (var component in components)
        {
            <tr>
                <td>@component.Name</td>
                <td>@component.ComponentManufacturer</td>
                <td style="white-space: pre">@component.Specifications</td>
                <td>@component.Cost</td>
                <td>@component.WarrantyPeriodMonths мес.</td>
            </tr>
        }
    </table>
</div>

<div>
    <form method="get" asp-controller="ComponentCategories" asp-action="Index" style="display: flex; width: 100%">
        <button type="submit" class="btn btn-light" style="flex-grow: 1; flex-basis: 0">Все категории комплектующих</button>
        <button type="button" onclick="history.back()" class="btn btn-light" style="flex-grow: 1; margin-left: 1%; flex-basis: 0">Назад</button>
    </form>
</div>

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/ComponentCategories/Edit.cshtml
@using static ComputerEquipmentMS.Views.Common.Constants
@model ComputerEquipmentMS.ViewModels.ComponentCategories.ComponentCategoryViewModel

<h2 class="display-4">Редактирование категории комплектующих</h2>

<div>
    <form asp-controller="ComponentCategories" asp-action="Edit" method="post">
        <div class="form-floating" style="margin-top: 20px">
            <input type="text" id="nameInput" asp-for="Name" class="form-control" required pattern="@DenyOnlySpacesOrSpaceFramesStringsRegex">
            <label for="nameInput">Название</label>
        </div>

        <div style="display: flex; width: 100%; margin-top: 20px">
            <button type="submit" class="btn btn-light" style="flex-grow: 1; flex-basis: 0">Сохранить</button>
            <button type="button" onclick="history.back()" class="btn btn-light" style="flex-grow: 1; flex-basis: 0; margin-left: 10px">Отменить</button>
        </div>
    </form>
</div>

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/ComponentCategories/Index.cshtml
@using ComputerEquipmentMS.Constants
@model ComputerEquipmentMS.ViewModels.ComponentCategories.ComponentCategoriesViewModel

@{
    var categories = Model;
    var userIsAdmin = User.IsInRole(RoleNames.Admin);
}

<h6 class="display-4">Категории комплектующих</h6>

<div name="components">
    <div style="text-align: right;">
        <form method="get" asp-controller="ComponentCategories" asp-action="Create">
            <button type="submit" class="btn btn-outline-dark">Добавить</button>
        </form>
    </div>
    <table class="table table-hover">
        <thread>
            <tr>
                <th>Название</th>
                <th/>
            </tr>
        </thread>
        @foreach (var category in categories)
        {
            <tr>
                <td>@category.Name</td>
                <td style="text-align: right;">
                    <form asp-controller="ComponentCategories">
                        <button type="submit" class="btn btn-outline-secondary btn-sm" asp-action="Details" asp-route-id="@category.Id" formmethod="get">Подробнее</button>
                        @if (userIsAdmin)
                        {
                            <button type="submit" class="btn btn-outline-secondary btn-sm" asp-action="Edit" asp-route-id="@category.Id" formmethod="get">Изменить</button>
                            <button type="submit" onclick="return confirmDeletion()" class="btn btn-outline-secondary btn-sm" asp-action="Remove" asp-route-id="@category.Id" formmethod="post">Удалить</button>
                        }
                    </form>
                </td>
            </tr>
        }
    </table>
</div>

<script src="~/js/componentCategories/index.js"></script>