src/ComputerEquipmentMS/ComputerEquipmentMS/Models/Domain/ComponentManufacturer.cs
namespace ComputerEquipmentMS.Models.Domain;

public class ComponentManufacturer : IIdentifiable<int>
{
    public int Id { get; set; }
    public required string Name { get; set; }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/ComponentManufacturerViewModel.cs
namespace ComputerEquipmentMS.ViewModels;

public class ComponentManufacturerViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/ComponentManufacturers/ComponentManufacturerViewModel.cs
namespace ComputerEquipmentMS.ViewModels.ComponentManufacturers;

public class ComponentManufacturerViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/ComponentManufacturers/ComponentManufacturersViewModel.cs
using System.Collections.ObjectModel;

namespace ComputerEquipmentMS.ViewModels.ComponentManufacturers;

public class ComponentManufacturersViewModel : Collection<ComponentManufacturerViewModel>
{
    public ComponentManufacturersViewModel(ICollection<ComponentManufacturerViewModel> manufacturerViewModels)
        : base(manufacturerViewModels.ToList())
    {
    }
    
    public ComponentManufacturersViewModel()
    {
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/ComponentManufacturersViewModel.cs
using System.Collections.ObjectModel;

namespace ComputerEquipmentMS.ViewModels;

public class ComponentManufacturersViewModel : Collection<ComponentManufacturerViewModel>
{
    public ComponentManufacturersViewModel(ICollection<ComponentManufacturerViewModel> manufacturerViewModels)
        : base(manufacturerViewModels.ToList())
    {
    }
    
    public ComponentManufacturersViewModel()
    {
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/ComponentManufacturersController.cs
using ComputerEquipmentMS.Constants;
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.ComponentCategories;
using ComputerEquipmentMS.ViewModels.ComponentManufacturers;
using ComputerEquipmentMS.ViewModels.Components;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ComputerEquipmentMS.Controllers;

public class ComponentManufacturersController : ControllerBase
{
    private readonly IRepository<ComponentManufacturer, int> _componentManufacturersRepository;
    private readonly NpgsqlStoredFunctionsExecutor _executor;

    public ComponentManufacturersController(
        IRepository<ComponentManufacturer, int> componentManufacturersRepository,
        NpgsqlStoredFunctionsExecutor executor,
        ILogger<ComponentManufacturersController> logger) : base(logger)
    {
        _componentManufacturersRepository = componentManufacturersRepository;
        _executor = executor;
    }
    
    

    [HttpGet]
    public IActionResult Index()
    {
        var manufacturers = _componentManufacturersRepository.GetAll();
        var manufacturersVm = manufacturers.Adapt<ComponentManufacturersViewModel>(); 
        
        return View(manufacturersVm);
    }

    
    
    [HttpGet]
    public IActionResult Details(int id)
    {
        var manufacturer = _componentManufacturersRepository.GetById(id);
        if (manufacturer is null) return HandleError($"cannot find {nameof(ComponentManufacturer)} with id = {id}");

        var components = _executor.GetComponentsByManufacturer(id);
        var componentsVm = components.Adapt<ComponentsViewModel>();
        ViewBag.Components = componentsVm; 
        
        var manufacturerVm = manufacturer.Adapt<ComponentCategoryViewModel>();
        return View(manufacturerVm);
    }
    
    
    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Create(ComponentManufacturerViewModel manufacturerViewModel)
    {
        var manufacturer = manufacturerViewModel.Adapt<ComponentManufacturer>();
        _componentManufacturersRepository.Add(manufacturer);

        return RedirectToAction(nameof(Index));
    }



    [HttpGet]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Edit(int id)
    {
        var manufacturer = _componentManufacturersRepository.GetById(id);
        if (manufacturer is null) return HandleError($"cannot find {nameof(ComponentManufacturer)} with id = {id}");

        var manufacturerVm = manufacturer.Adapt<ComponentManufacturerViewModel>();
        return View(manufacturerVm);
    }
    
    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Edit(ComponentManufacturerViewModel manufacturerViewModel)
    {
        var manufacturer = manufacturerViewModel.Adapt<ComponentManufacturer>();
        var editResult = _componentManufacturersRepository.Edit(manufacturer);
        return editResult 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while editing {nameof(ComponentManufacturer)}: element with id {manufacturer.Id} was not edited");
    }
    
    

    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Remove(int id)
    {
        var removeResult = _componentManufacturersRepository.Remove(id);
        return removeResult 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while removing {nameof(ComponentManufacturer)}: element with id {id} was not removing");
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/ComponentManufacturers/Create.cshtml
@model ComputerEquipmentMS.ViewModels.ComponentManufacturers.ComponentManufacturerViewModel

<h2 class="display-4">Добавление производителя комплектующих</h2>

<div>
    <form asp-controller="ComponentManufacturers" asp-action="Create" method="post">
        <div class="form-floating" style="margin-top: 20px">
            <input type="text" id="nameInput" asp-for="Name" class="form-control" required>
            <label for="nameInput">Название</label>
        </div>

        <div style="display: flex; width: 100%; margin-top: 20px">
            <button type="submit" class="btn btn-light" style="flex-grow: 1; flex-basis: 0">Сохранить</button>
            <button type="button" onclick="history.back()" class="btn btn-light" style="flex-grow: 1; flex-basis: 0; margin-left: 10px">Отменить</button>
        </div>
    </form>
</div>

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/ComponentManufacturers/Details.cshtml
@using ComputerEquipmentMS.ViewModels.Components
@model ComputerEquipmentMS.ViewModels.ComponentCategories.ComponentCategoryViewModel

@{
    var manufacturer = Model;

    var components = (ComponentsViewModel) ViewBag.Components;
}

@* <h2 class="display-4">@manufacturer.Name</h2> *@

<div>
    <h2 class="display-6">Компоненты от производителя "@manufacturer.Name"</h2>
    
    <table class="table table-hover">
        <thread>
            <tr>
                <th>Название</th>
                <th>Категория</th>
                <th>Спецификации</th>
                <th>Стоимость закупки у производителя</th>
                <th>Гарантия производителя</th>
            </tr>
        </thread>
        @foreach (var component in components)
        {
            <tr>
                <td>@component.Name</td>
                <td>@component.ComponentCategory</td>
                <td style="white-space: pre">@component.Specifications</td>
                <td>@component.Cost</td>
                <td>@component.WarrantyPeriodMonths мес.</td>
            </tr>
        }
    </table>
    <form method="get" asp-controller="ComponentManufacturers" asp-action="Index" style="display: flex; width: 100%">
        <button type="submit" class="btn btn-light" style="flex-grow: 1; flex-basis: 0">Все производители комплектующих</button>
        <button type="button" onclick="history.back()" class="btn btn-light" style="flex-grow: 1; margin-left: 1%; flex-basis: 0">Назад</button>
    </form>
</div>

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/ComponentManufacturers/Edit.cshtml
@using static ComputerEquipmentMS.Views.Common.Constants
@model ComputerEquipmentMS.ViewModels.ComponentManufacturers.ComponentManufacturerViewModel

<h2 class="display-4">Редактирование производителя комплектующих</h2>

<div>
    <form asp-controller="ComponentManufacturers" asp-action="Edit" method="post">
        <div class="form-floating" style="margin-top: 20px">
            <input type="text" id="nameInput" asp-for="Name" class="form-control" required pattern="@DenyOnlySpacesOrSpaceFramesStringsRegex">
            <label for="nameInput">Название</label>
        </div>

        <div style="display: flex; width: 100%; margin-top: 20px">
            <button type="submit" class="btn btn-light" style="flex-grow: 1; flex-basis: 0">Сохранить</button>
            <button type="button" onclick="history.back()" class="btn btn-light" style="flex-grow: 1; flex-basis: 0; margin-left: 10px">Отменить</button>
        </div>
    </form>
</div>

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/ComponentManufacturers/Index.cshtml
@using ComputerEquipmentMS.Constants
@model ComputerEquipmentMS.ViewModels.ComponentManufacturers.ComponentManufacturersViewModel

@{
    var manufacturers = Model;
    var userIsAdmin = User.IsInRole(RoleNames.Admin);
}

<h6 class="display-4">Производители комплектующих</h6>

<div name="components">
    <div style="text-align: right;">
        <form method="get" asp-controller="ComponentManufacturers" asp-action="Create">
            <button type="submit" class="btn btn-outline-dark">Добавить</button>
        </form>
    </div>
    <table class="table table-hover">
        <thread>
            <tr>
                <th>Название</th>
                <th/>
            </tr>
        </thread>
        @foreach (var manufacturer in manufacturers)
        {
            <tr>
                <td>@manufacturer.Name</td>
                <td style="text-align: right;">
                    <form asp-controller="ComponentManufacturers">
                        <button type="submit" class="btn btn-outline-secondary btn-sm" asp-action="Details" asp-route-id="@manufacturer.Id" formmethod="get">Подробнее</button>
                        @if (userIsAdmin)
                        {
                            <button type="submit" class="btn btn-outline-secondary btn-sm" asp-action="Edit" asp-route-id="@manufacturer.Id" formmethod="get">Изменить</button>
                            <button type="submit" onclick="return confirmDeletion()" class="btn btn-outline-secondary btn-sm" asp-action="Remove" asp-route-id="@manufacturer.Id" formmethod="post">Удалить</button>
                        }
                    </form>
                </td>
            </tr>
        }
    </table>
</div>

<script src="~/js/componentManufacturers/index.js"></script>