src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/ComponentsController.cs
using ComputerEquipmentMS.Constants;
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.ComponentCategories;
using ComputerEquipmentMS.ViewModels.ComponentManufacturers;
using ComputerEquipmentMS.ViewModels.Components;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ComputerEquipmentMS.Controllers;

public class ComponentsController : ControllerBase
{
    private readonly IRepository<Component, int> _componentsRepository;
    private readonly IRepository<ComponentCategory, int> _componentCategoriesRepository;
    private readonly IRepository<ComponentManufacturer, int> _componentManufacturersRepository;

    public ComponentsController(
        IRepository<Component, int> componentsRepository, 
        IRepository<ComponentCategory, int> componentCategoriesRepository, 
        IRepository<ComponentManufacturer, int> componentManufacturersRepository, 
        ILogger<ComponentsController> logger) : base(logger)
    {
        _componentsRepository = componentsRepository;
        _componentCategoriesRepository = componentCategoriesRepository;
        _componentManufacturersRepository = componentManufacturersRepository;
    }

    public IActionResult Index()
    {
        var components = _componentsRepository.GetAll();
        
        var componentVms = components.Adapt<List<ComponentViewModel>>();
        var componentsVm = new ComponentsViewModel(componentVms);
        
        return View(componentsVm);
    }

    
    
    [HttpGet]
    public IActionResult Create()
    {
        var componentCategories = _componentCategoriesRepository.GetAll();
        var componentManufacturers = _componentManufacturersRepository.GetAll();

        var componentCategoryVms = componentCategories.Adapt<List<ComponentCategoryViewModel>>();
        var componentManufacturerVms = componentManufacturers.Adapt<List<ComponentManufacturerViewModel>>();
        
        ViewBag.ComponentCategories = componentCategoryVms;
        ViewBag.ComponentManufacturers = componentManufacturerVms;
        
        return View();
    }

    [HttpPost]
    public IActionResult Create(ComponentViewModel componentVm)
    {
        var component = componentVm.Adapt<Component>();
        _componentsRepository.Add(component);

        return RedirectToAction(nameof(Index));
    }



    [HttpGet]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Edit(int id)
    {
        var component = _componentsRepository.GetById(id);
        if (component is null) return HandleError($"cannot find {nameof(Component)} with id = {id}");

        ViewBag.Specifications = component.Specifications;
        var componentVm = component.Adapt<ComponentViewModel>();

        var componentCategories = _componentCategoriesRepository.GetAll();
        var componentManufacturers = _componentManufacturersRepository.GetAll();

        var componentCategoryVms = componentCategories.Adapt<List<ComponentCategoryViewModel>>();
        var componentManufacturerVms = componentManufacturers.Adapt<List<ComponentManufacturerViewModel>>();
        
        ViewBag.ComponentCategories = componentCategoryVms;
        ViewBag.ComponentManufacturers = componentManufacturerVms;
        
        return View(componentVm);
    }
    
    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Edit(ComponentViewModel componentViewModel)
    {
        var component = componentViewModel.Adapt<Component>();

        var editResult = _componentsRepository.Edit(component);
        return editResult 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while updating {nameof(Component)}: element with id {component.Id} was not updated");
    }
    
    

    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Remove(int id)
    {
        var result = _componentsRepository.Remove(id);
        return result 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while removing {nameof(Component)}: element with id {id} was not removing");
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/CustomersController.cs
using ComputerEquipmentMS.Constants;
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.Customers;
using ComputerEquipmentMS.ViewModels.Sales;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NodaTime;

namespace ComputerEquipmentMS.Controllers;

public class CustomersController : ControllerBase
{
    private readonly IRepository<Customer, int> _customersRepository;
    private readonly NpgsqlStoredFunctionsExecutor _functionsExecutor;

    public CustomersController(
        IRepository<Customer, int> customersRepository,
        NpgsqlStoredFunctionsExecutor functionsExecutor,
        ILogger<CustomersController> logger) : base(logger)
    {
        _customersRepository = customersRepository;
        _functionsExecutor = functionsExecutor;
    }
    
    public IActionResult Index()
    {
        var customers = _customersRepository.GetAll();

        var customerViewModels = customers.Adapt<List<CustomerDetailsViewModel>>();
        var customersViewModel = new CustomersViewModel(customerViewModels); 
        
        return View(customersViewModel);
    }

    
    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Create(CustomerDetailsViewModel newCustomerVm)
    {
        var newCustomer = newCustomerVm.Adapt<Customer>();
        
        newCustomer.RegistrationDate = LocalDate.FromDateTime(DateTime.Now);
        _customersRepository.Add(newCustomer);
        
        return RedirectToAction(nameof(Index));
    }
    
    
    
    [HttpGet]
    public IActionResult Details(int id)
    {
        var customer = _customersRepository.GetById(id);
        if (customer is null) return HandleError($"cannot find {nameof(Customer)} with id = {id}");

        var purchases = _functionsExecutor.GetCustomersPurchases(id);
        var purchaseVms = purchases.Adapt<List<SaleDetailsViewModel>>();
        
        var customerVm = customer.Adapt<CustomerWithPurchasesViewModel>();
        customerVm.Purchases = purchaseVms;
        
        return View(customerVm);
    }
    
    
    
    [HttpGet]
    public IActionResult Edit(int id)
    {
        var customer = _customersRepository.GetById(id);
        if (customer is null) return HandleError($"cannot find {nameof(Customer)} with id = {id}");

        var customerVm = customer.Adapt<CustomerDetailsViewModel>();
        return View(customerVm);
    }
    
    [HttpPost]
    public IActionResult Edit(CustomerDetailsViewModel customerViewModel)
    {
        var customer = customerViewModel.Adapt<Customer>();

        var result = _customersRepository.Edit(customer);
        if (result) return RedirectToAction(nameof(Index));

        return result
            ? RedirectToAction(nameof(Index))
            : HandleError($"error while editing {nameof(Customer)}: element with id {customer.Id} was not edited");
    }
    
    
    
    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Remove(int id)
    {
        var result = _customersRepository.Remove(id);
        return result 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while removing {nameof(Customer)}: element with id {id} was not removed");
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/ReportsController.cs
using ComputerEquipmentMS.Constants;
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Auxiliary;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.ComputerConfigurations;
using ComputerEquipmentMS.ViewModels.Customers;
using ComputerEquipmentMS.ViewModels.SalePositions;
using ComputerEquipmentMS.ViewModels.Sales;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NodaTime;

namespace ComputerEquipmentMS.Controllers;

public class ReportsController : Controller
{
    private readonly IRepository<ComputerConfiguration, int> _configurationsRepository;
    private readonly IRepository<Customer, int> _customersRepository;
    private readonly NpgsqlStoredFunctionsExecutor _executor;

    public ReportsController(
        IRepository<ComputerConfiguration, int> configurationsRepository,
        IRepository<Customer, int> customersRepository,
        NpgsqlStoredFunctionsExecutor executor)
    {
        _configurationsRepository = configurationsRepository;
        _customersRepository = customersRepository;
        _executor = executor;
    }

    public IActionResult Index()
    {
        return View();
    }
    
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult GetComputerConfigurationsSales(int configurationId, DateOnly from, DateOnly until)
    {
        SetTodayIfDatesAreMinValue(ref from, ref until);        
        
        var timeInterval = CreateTimeInterval(from, until);
        var salePositions = _executor.GetSalesOfConfigurationForTimeInterval(configurationId, timeInterval);
        var salePositionsVm = salePositions.Adapt<List<SalePositionInfoViewModel>>();

        ViewBag.From = from;
        ViewBag.Until = until;
        ViewBag.CurrentConfigurationId = configurationId;
        
        var configurations = _configurationsRepository.GetAll();
        var configurationsVm = configurations.Adapt<ComputerConfigurationsViewModel>();
        ViewBag.Configurations = configurationsVm;
        
        return View(salePositionsVm);
    }
    
    public IActionResult GetCustomersPurchases(int customerId, DateOnly from, DateOnly until)
    {
        SetTodayIfDatesAreMinValue(ref from, ref until); 
        
        var timeInterval = CreateTimeInterval(from, until);
        var sales = _executor.GetCustomersPurchases(customerId, timeInterval);
        var salesVm = sales.Adapt<SalesViewModel>();

        ViewBag.From = from;
        ViewBag.Until = until;
        ViewBag.CurrentCustomerId = customerId;
        
        var customers = _customersRepository.GetAll();
        var customersVm = customers.Adapt<CustomersViewModel>();
        ViewBag.Customers = customersVm;
        
        return View(salesVm);
    }



    private static TimeInterval CreateTimeInterval(DateOnly from, DateOnly until) =>
        new (DateOnlyToInstant(from, new TimeOnly(0, 0)), DateOnlyToInstant(until, new TimeOnly(23, 59)));

    private static Instant DateOnlyToInstant(DateOnly d, TimeOnly maxTime) => 
        Instant.FromUtc(d.Year, d.Month, d.Day, maxTime.Hour, maxTime.Minute);

    private static void SetTodayIfDatesAreMinValue(ref DateOnly from, ref DateOnly until)
    {
        if (from == DateOnly.MinValue) from = GetToday();
        if (until == DateOnly.MinValue) until = GetToday();
    }
    
    private static DateOnly GetToday() =>
        DateOnly.FromDateTime(DateTime.Today);
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/SalesController.cs
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.ComputerConfigurations;
using ComputerEquipmentMS.ViewModels.Customers;
using ComputerEquipmentMS.ViewModels.Sales;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using NodaTime;
using NodaTime.Extensions;

namespace ComputerEquipmentMS.Controllers;

public class SalesController : ControllerBase
{
    private readonly IRepository<Sale, int> _salesRepository;
    private readonly IRepository<ComputerConfiguration, int> _configurationsRepository;
    private readonly IRepository<Customer, int> _customersRepository;
    private readonly NpgsqlStoredFunctionsExecutor _executor;

    public SalesController(
        IRepository<Sale, int> salesRepository,
        IRepository<ComputerConfiguration, int> configurationsRepository,
        IRepository<Customer, int> customersRepository,
        NpgsqlStoredFunctionsExecutor executor,
        ILogger<SalesController> logger) : base(logger)
    {
        _salesRepository = salesRepository;
        _configurationsRepository = configurationsRepository;
        _customersRepository = customersRepository;
        _executor = executor;
    }
    
    public IActionResult Index()
    {
        var sales = _salesRepository.GetAll();
        
        var saleVms = sales.Adapt<List<SaleDetailsViewModel>>();
        var salesVm = new SalesViewModel(saleVms);
        
        return View(salesVm);
    }

    [HttpGet]
    public IActionResult Details(int id)
    {
        var sale = _salesRepository.GetById(id);
        if (sale is null) return HandleError($"cannot find {nameof(Sale)} with id = {id}");

            var saleVm = sale.Adapt<SaleDetailsViewModel>();
        return View(saleVm);
    }

    [HttpGet]
    public IActionResult Create()
    {
        var computerConfigurations = _configurationsRepository.GetAll();
        var computerConfigurationsInfo = computerConfigurations.Adapt<List<ComputerConfigurationInfoViewModel>>(); 
        ViewBag.ComputerConfigurations = computerConfigurationsInfo;

        var customers = _customersRepository.GetAll();
        var customersVm = customers.Adapt<CustomersViewModel>();
        ViewBag.Customers = customersVm;
        
        return View();
    }

    [HttpPost]
    public IActionResult Create(CreateSaleViewModel saleViewModel)
    {
        var sale = saleViewModel.Adapt<Sale>();
        
        var currentMomentWithTimeZone = Instant.FromDateTimeUtc(DateTime.UtcNow) + TimeZoneInfo.Local.BaseUtcOffset.ToDuration();
        sale.SaleMoment = currentMomentWithTimeZone;
        
        _executor.CreateSale(sale);
            
        return RedirectToAction(nameof(Index));
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using ComputerEquipmentMS.Constants

@{
    var userIsAdmin = User.IsInRole(RoleNames.Admin);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Система учета компьютерных сборок</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/custom-styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Sales" asp-action="Index">Система учета компьютерных сборок</a>
            <div class="vr"></div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Продажи</a>
                    </li>
                    <div class="vr"></div>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Покупатели</a>
                    </li>
                    <div class="vr"></div>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Configurations" asp-action="Index">Сборки</a>
                    </li>
                    <div class="vr"></div>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Components" asp-action="Index">Комплектующие</a>
                    </li>
                    <div class="vr"></div>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ComponentCategories" asp-action="Index">Категории комплектующих</a>
                    </li>
                    <div class="vr"></div>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ComponentManufacturers" asp-action="Index">Производители комплектующих</a>
                    </li>
                    <div class="vr"></div>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Отчёты</a>
                    </li>
                    <div class="vr"></div>
                </ul>   
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>