src/ComputerEquipmentMS/ComputerEquipmentMS/Models/Domain/Sale.cs
using NodaTime;

namespace ComputerEquipmentMS.Models.Domain;

public class Sale : IIdentifiable<int>
{
    public int Id { get; set; }
    
    public required Customer Customer { get; set; }
    
    public Instant SaleMoment  { get; set; }
    
    public decimal StartingCost { get; set; }

    public short DiscountPercentage { get; set; }

    public ICollection<SalePosition> SalePositions { get; set; } = new List<SalePosition>();
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/SaleViewModel.cs
using NodaTime;

namespace ComputerEquipmentMS.ViewModels;

public class SaleViewModel
{
    public int Id { get; set; }
    
    public Instant SaleMoment  { get; set; }

    public decimal StartingCost { get; set; }
    public short DiscountPercentage { get; set; }
    public decimal FinalCost { get; set; }

    public required ICollection<SalePositionViewModel> SalePositions { get; set; }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/Sales/CreateSaleViewModel.cs
namespace ComputerEquipmentMS.ViewModels.Sales;

public class CreateSaleViewModel : SaleViewModelBase
{
    public int CustomerId { get; set; }
    public string ComputerConfigurationIdsWithDiscountsJson { get; set; } = string.Empty;
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/Sales/SaleDetailsViewModel.cs
using ComputerEquipmentMS.ViewModels.Customers;
using ComputerEquipmentMS.ViewModels.SalePositions;

namespace ComputerEquipmentMS.ViewModels.Sales;

public class SaleDetailsViewModel : SaleInfoViewModel
{
    public required CustomerInfoViewModel Customer;
    public required ICollection<SalePositionDetailsViewModel> SalePositions { get; set; }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/Sales/SaleInfoViewModel.cs
using NodaTime;

namespace ComputerEquipmentMS.ViewModels.Sales;

public class SaleInfoViewModel : SaleViewModelBase
{
    public Instant SaleMoment  { get; set; }
    public decimal StartingCost { get; set; }
    public decimal FinalCost { get; set; }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/Sales/SaleViewModelBase.cs
namespace ComputerEquipmentMS.ViewModels.Sales;

public class SaleViewModelBase
{
    public int Id { get; set; }
    public int DiscountPercentage { get; set; }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/Sales/SalesViewModel.cs
using System.Collections.ObjectModel;

namespace ComputerEquipmentMS.ViewModels.Sales;

public class SalesViewModel : Collection<SaleDetailsViewModel>
{
    public SalesViewModel(IEnumerable<SaleDetailsViewModel> sales)
        : base(sales.ToList())
    {
    }

    public SalesViewModel()
    {
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/ViewModels/SalesViewModel.cs
using System.Collections.ObjectModel;

namespace ComputerEquipmentMS.ViewModels;

public class SalesViewModel : Collection<SaleDetailsViewModel>
{
    public SalesViewModel(IEnumerable<SaleDetailsViewModel> sales)
        : base(sales.ToList())
    {
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/ConfigurationsController.cs
using ComputerEquipmentMS.Constants;
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.Components;
using ComputerEquipmentMS.ViewModels.ComputerConfigurations;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ComputerEquipmentMS.Controllers;

public class ConfigurationsController : ControllerBase
{
    private readonly IRepository<ComputerConfiguration, int> _configurationRepository;
    private readonly IRepository<Component, int> _componentRepository;

    public ConfigurationsController(
        IRepository<ComputerConfiguration, int> configurationRepository,
        IRepository<Component, int> componentRepository,
        ILogger<ConfigurationsController> logger) : base(logger)
    {
        _configurationRepository = configurationRepository;
        _componentRepository = componentRepository;
    }

    public IActionResult Index()
    {
        var configurations = _configurationRepository.GetAll();
        
        var configurationVms = configurations.Adapt<List<ComputerConfigurationDetailsViewModel>>();
        var configurationsVm = new ComputerConfigurationsViewModel(configurationVms);
        
        return View(configurationsVm);
    }



    [HttpGet]
    public IActionResult Create()
    {
        var components = _componentRepository.GetAll();
        var componentVms = components.Adapt<ComponentsViewModel>();
        ViewBag.Components = componentVms;
        
        return View();
    }
    
    [HttpPost]
    public IActionResult Create(CreateComputerConfigurationViewModel configurationViewModel)
    {
        var configuration = configurationViewModel.Adapt<ComputerConfiguration>();
        _configurationRepository.Add(configuration);

        return RedirectToAction(nameof(Index));
    }

    
    
    [HttpGet]
    public IActionResult Details(int id)
    {
        var config = _configurationRepository.GetById(id);
        if (config is null) return HandleError($"cannot find {nameof(ComputerConfiguration)} with id = {id}");
        
        var configViewModel = config.Adapt<ComputerConfigurationDetailsViewModel>();
        return View(configViewModel);
    }

    
    
    [HttpGet]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Edit(int id)
    {
        var configuration = _configurationRepository.GetById(id);
        if (configuration is null) return HandleError($"cannot find {nameof(ComputerConfiguration)} with id = {id}");

        var components = _componentRepository.GetAll();
        var componentVms = components.Adapt<ComponentsViewModel>();
        ViewBag.Components = componentVms;
        
        var configurationVm = configuration.Adapt<EditComputerConfigurationViewModel>();
        return View(configurationVm);
    }

    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Edit(EditComputerConfigurationViewModel configViewModel)
    {
        var configuration = configViewModel.Adapt<ComputerConfiguration>();
        _configurationRepository.Edit(configuration);

        return RedirectToAction(nameof(Index));
    }


    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Remove(int id)
    {
        var removeResult = _configurationRepository.Remove(id);
        return removeResult 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while removing {nameof(ComputerConfiguration)}: element with id {id} was not removed");
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/CustomersController.cs
using ComputerEquipmentMS.Constants;
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.Customers;
using ComputerEquipmentMS.ViewModels.Sales;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NodaTime;

namespace ComputerEquipmentMS.Controllers;

public class CustomersController : ControllerBase
{
    private readonly IRepository<Customer, int> _customersRepository;
    private readonly NpgsqlStoredFunctionsExecutor _functionsExecutor;

    public CustomersController(
        IRepository<Customer, int> customersRepository,
        NpgsqlStoredFunctionsExecutor functionsExecutor,
        ILogger<CustomersController> logger) : base(logger)
    {
        _customersRepository = customersRepository;
        _functionsExecutor = functionsExecutor;
    }
    
    public IActionResult Index()
    {
        var customers = _customersRepository.GetAll();

        var customerViewModels = customers.Adapt<List<CustomerDetailsViewModel>>();
        var customersViewModel = new CustomersViewModel(customerViewModels); 
        
        return View(customersViewModel);
    }

    
    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Create(CustomerDetailsViewModel newCustomerVm)
    {
        var newCustomer = newCustomerVm.Adapt<Customer>();
        
        newCustomer.RegistrationDate = LocalDate.FromDateTime(DateTime.Now);
        _customersRepository.Add(newCustomer);
        
        return RedirectToAction(nameof(Index));
    }
    
    
    
    [HttpGet]
    public IActionResult Details(int id)
    {
        var customer = _customersRepository.GetById(id);
        if (customer is null) return HandleError($"cannot find {nameof(Customer)} with id = {id}");

        var purchases = _functionsExecutor.GetCustomersPurchases(id);
        var purchaseVms = purchases.Adapt<List<SaleDetailsViewModel>>();
        
        var customerVm = customer.Adapt<CustomerWithPurchasesViewModel>();
        customerVm.Purchases = purchaseVms;
        
        return View(customerVm);
    }
    
    
    
    [HttpGet]
    public IActionResult Edit(int id)
    {
        var customer = _customersRepository.GetById(id);
        if (customer is null) return HandleError($"cannot find {nameof(Customer)} with id = {id}");

        var customerVm = customer.Adapt<CustomerDetailsViewModel>();
        return View(customerVm);
    }
    
    [HttpPost]
    public IActionResult Edit(CustomerDetailsViewModel customerViewModel)
    {
        var customer = customerViewModel.Adapt<Customer>();

        var result = _customersRepository.Edit(customer);
        if (result) return RedirectToAction(nameof(Index));

        return result
            ? RedirectToAction(nameof(Index))
            : HandleError($"error while editing {nameof(Customer)}: element with id {customer.Id} was not edited");
    }
    
    
    
    [HttpPost]
    [Authorize(Roles = RoleNames.Admin)]
    public IActionResult Remove(int id)
    {
        var result = _customersRepository.Remove(id);
        return result 
            ? RedirectToAction(nameof(Index)) 
            : HandleError($"error while removing {nameof(Customer)}: element with id {id} was not removed");
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Controllers/SalesController.cs
using ComputerEquipmentMS.DataAccess;
using ComputerEquipmentMS.Models.Domain;
using ComputerEquipmentMS.ViewModels.ComputerConfigurations;
using ComputerEquipmentMS.ViewModels.Customers;
using ComputerEquipmentMS.ViewModels.Sales;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using NodaTime;
using NodaTime.Extensions;

namespace ComputerEquipmentMS.Controllers;

public class SalesController : ControllerBase
{
    private readonly IRepository<Sale, int> _salesRepository;
    private readonly IRepository<ComputerConfiguration, int> _configurationsRepository;
    private readonly IRepository<Customer, int> _customersRepository;
    private readonly NpgsqlStoredFunctionsExecutor _executor;

    public SalesController(
        IRepository<Sale, int> salesRepository,
        IRepository<ComputerConfiguration, int> configurationsRepository,
        IRepository<Customer, int> customersRepository,
        NpgsqlStoredFunctionsExecutor executor,
        ILogger<SalesController> logger) : base(logger)
    {
        _salesRepository = salesRepository;
        _configurationsRepository = configurationsRepository;
        _customersRepository = customersRepository;
        _executor = executor;
    }
    
    public IActionResult Index()
    {
        var sales = _salesRepository.GetAll();
        
        var saleVms = sales.Adapt<List<SaleDetailsViewModel>>();
        var salesVm = new SalesViewModel(saleVms);
        
        return View(salesVm);
    }

    [HttpGet]
    public IActionResult Details(int id)
    {
        var sale = _salesRepository.GetById(id);
        if (sale is null) return HandleError($"cannot find {nameof(Sale)} with id = {id}");

            var saleVm = sale.Adapt<SaleDetailsViewModel>();
        return View(saleVm);
    }

    [HttpGet]
    public IActionResult Create()
    {
        var computerConfigurations = _configurationsRepository.GetAll();
        var computerConfigurationsInfo = computerConfigurations.Adapt<List<ComputerConfigurationInfoViewModel>>(); 
        ViewBag.ComputerConfigurations = computerConfigurationsInfo;

        var customers = _customersRepository.GetAll();
        var customersVm = customers.Adapt<CustomersViewModel>();
        ViewBag.Customers = customersVm;
        
        return View();
    }

    [HttpPost]
    public IActionResult Create(CreateSaleViewModel saleViewModel)
    {
        var sale = saleViewModel.Adapt<Sale>();
        
        var currentMomentWithTimeZone = Instant.FromDateTimeUtc(DateTime.UtcNow) + TimeZoneInfo.Local.BaseUtcOffset.ToDuration();
        sale.SaleMoment = currentMomentWithTimeZone;
        
        _executor.CreateSale(sale);
            
        return RedirectToAction(nameof(Index));
    }
}

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/Sales/Create.cshtml
@using ComputerEquipmentMS.ViewModels.ComputerConfigurations
@using ComputerEquipmentMS.ViewModels.Customers
@model ComputerEquipmentMS.ViewModels.Sales.CreateSaleViewModel

@{
    var configurations = (ICollection<ComputerConfigurationInfoViewModel>) ViewBag.ComputerConfigurations;
    var customers = (CustomersViewModel) ViewBag.Customers;
    
    var customersSelectList = new SelectList(customers, nameof(CustomerDetailsViewModel.Id), nameof(CustomerDetailsViewModel.Name));
}

<h2 class="display-4">Создание продажи</h2>

<div>
    <form asp-controller="Sales" asp-action="Create" method="post" onsubmit="return checkConfigurationsSelection()">
        <div class="form-floating" style="margin-top: 20px">
            <input type="number" min="0" max="100" id="discountPercentage" asp-for="DiscountPercentage" class="form-control" required>
            <label for="discountPercentage">Общая скидка в процентах</label>
        </div>
        
        <div class="form-floating" style="margin-top: 20px">
            <select id="customerIdSelect" asp-for="CustomerId" asp-items="@customersSelectList" class="form-select"></select>
            <label for="customerIdSelect">Покупатель</label>
        </div>

        <div id="components">
            <h2 class="display-6">Компьютерные сборки</h2>
            <input id="configurationIdsWithDiscountsJsonCollector" type="text" asp-for="ComputerConfigurationIdsWithDiscountsJson" hidden>
            <input id="configurationIdsWithDiscountsJsonCollectorNotEmpty" type="checkbox" hidden>
            <table class="table table-hover">
                <thread>
                    <tr>
                        <th/>
                        <th>Название</th>
                        <th>Гарантия</th>
                        <th>Выручка</th>
                        <th>Скидка при продаже</th>
                    </tr>
                </thread>
                @foreach (var configuration in configurations)
                {
                    <tr>
                        <td><input type="checkbox" id="checkboxConfiguration-@configuration.Id" class="form-check-input" style="height: 25px; width: 25px"></td>
                        <td>
                            <a asp-controller="Configurations" asp-action="Details" asp-route-id="@configuration.Id">@configuration.Name</a>
                        </td>
                        <td>@configuration.WarrantyPeriodMonths мес.</td>
                        <td>@configuration.Margin</td>
                        <td>
                            <input id="discountInput-@configuration.Id" type="number" min="0" max="100" value="0" class="form-control" required>
                        </td>
                    </tr>
                }
            </table>
        </div>    
        
        <div style="display: flex; width: 100%; margin-top: 20px">
            <button type="submit" onclick="collectConfigurationIdsWithDiscountsIntoCollector()" class="btn btn-light" style="flex-grow: 1; flex-basis: 0">Сохранить</button>
            <button type="button" onclick="history.back()" class="btn btn-light" style="flex-grow: 1; flex-basis: 0; margin-left: 10px">Отменить</button>
        </div>
    </form>
</div>

<script src="~/js/sales/create.js"></script>

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/Sales/Details.cshtml
@using static ComputerEquipmentMS.Views.Common.Formatter
@using static ComputerEquipmentMS.Views.Common.Converter
@model ComputerEquipmentMS.ViewModels.Sales.SaleDetailsViewModel

@{
    var sale = Model;
    var salePositions = sale.SalePositions; 
}

<h1 class="display-4">Детали продажи</h1>

<div>
    <table class="table table-hover">
        <thread>
            <tr>
                <th>Покупатель</th>
                <th>Дата продажи</th>
                <th>Время продажи</th>
                <th>Начальная цена</th>
                <th>Скидка, %</th>
                <th>Конечная цена</th>
            </tr>
        </thread>
        <tr>
            <td>
                <a asp-controller="Customers" asp-action="Details" asp-route-id="@sale.Customer.Id">@sale.Customer.Name</a>
            </td>
            <td>@LocalDateFromInstant(sale.SaleMoment)</td>
            <td>@FormatInstantToTime(sale.SaleMoment)</td>
            <td>@sale.StartingCost</td>
            <td>@sale.DiscountPercentage</td>
            <td>@sale.FinalCost</td>
        </tr>
    </table>
</div>

<div>
    <h5 class="display-6">Позиции продажи</h5>
    <table class="table table-hover">
        <thread>
            <tr>
                <th>Сборка</th>
                <th>Начальная цена</th>
                <th>Скидка, %</th>
                <th>Конечная цена</th>
                <th>Гарантийный период</th>
            </tr>
        </thread>
        @foreach (var salePosition in salePositions)
        {
            <tr>
                <td>
                    <a asp-controller="Configurations" asp-action="Details" asp-route-id="@salePosition.ComputerConfigurationId">
                        @salePosition.ComputerConfigurationName
                    </a>
                </td>
                <td>@salePosition.StartingCost</td>
                <td>@salePosition.DiscountPercentage</td>
                <td>@salePosition.FinalCost</td>
                <td>@FormatPeriodToString(@salePosition.WarrantyPeriod)</td>
            </tr>
        }
    </table>
</div>

<div>
    <form method="get" asp-controller="Sales" asp-action="Index" style="display: flex; width: 100%">
        <button type="submit" class="btn btn-light" style="flex-grow: 1; flex-basis: 0">Все продажи</button>
        <button type="button" onclick="history.back()" class="btn btn-light" style="flex-grow: 1; margin-left: 1%; flex-basis: 0">Назад</button>
    </form>
</div>

src/ComputerEquipmentMS/ComputerEquipmentMS/Views/Sales/Index.cshtml
@using static ComputerEquipmentMS.Views.Common.Formatter
@using static ComputerEquipmentMS.Views.Common.Converter
@model ComputerEquipmentMS.ViewModels.Sales.SalesViewModel

@{
    var sales = Model;
}

<h1 class="display-4">Продажи</h1>

<div name="sales">
    <div style="text-align: right;">
        <form method="get" asp-controller="Sales" asp-action="Create">
            <button type="submit" class="btn btn-outline-dark">Добавить</button>
        </form>
    </div>
    <table class="table table-hover">
        <thread>
            <tr>
                <th>Дата продажи</th>
                <th>Время продажи</th>
                <th>Начальная цена</th>
                <th>Скидка, %</th>
                <th>Конечная цена</th>
                <th/>
            </tr>
        </thread>
        @foreach (var sale in sales)
        {
            <tr>
                <td>@LocalDateFromInstant(sale.SaleMoment)</td>
                <td>@FormatInstantToTime(sale.SaleMoment)</td>
                <td>@sale.StartingCost</td>
                <td>@sale.DiscountPercentage</td>
                <td>@sale.FinalCost</td>
                <td style="text-align: right;">
                    <form asp-controller="Sales" asp-action="Details" asp-route-id="@sale.Id" method="get">
                        <button type="submit" class="btn btn-outline-secondary btn-sm">Подробнее</button>
                    </form>
                </td>
            </tr>
        }
    </table>
</div>